### PR TITLE
Docs: Adds a note about page definition order and routes

### PR DESCRIPTION
**Pull request by cstuder**

### CODE REVIEW

**Comment by julians300** [comment]
I'm not sure if this is needed. It seems more like a react-router-dom specification. 

Also you can use `exact` to match the route exactly, meaning `/edit` will only match exactly that and not `/edit/:id`. Maybe in the notes, instead of explaining, link to the docs. What do you think @cstuder?

Thanks :)

**Comment by cstuder** [comment]
I've been documenting the stuff I had to research when using the dashboard, so from my point of view I would have welcomed a note about the page ordering.

For example I didn't knew that I could use `exact` in the page definition list. That would be a cleaner solution.

You know what, I'll reword the docs in this pull request and add a note directly to the pages list.

**Comment by cstuder** [comment]
Updated.

**Review by julians300 — APPROVED** [review]
Looks good thanks!

**Pull request merged**
